name: dev_branch_tag_increment
description: Autoincrement tag for minor

runs:
  using: composite
  steps:
    - name: Autoincrement tag for minor
      shell: bash
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "Latest tag: $LAST_TAG"

        VERSION=${LAST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

        MINOR=$((MINOR + 1))
        PATCH=0
        NEW_TAG="v$MAJOR.$MINOR.$PATCH"

        echo "Create tag: $NEW_TAG"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a $NEW_TAG -m "Auto tag $NEW_TAG"
        git push origin $NEW_TAG || echo "Tag already exist"