spring:
  application:
    name: "inkonpaper"

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:${DB_SUBPROTOCOL}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: ${DB_DRIVER}

server:
  port: ${APPLICATION_PORT}