spring:
  datasource:
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: jdbc:${LOCAL_DB_SUBPROTOCOL}://${LOCAL_DB_HOST:localhost}:${LOCAL_DB_PORT}/${LOCAL_DB_NAME}
    driver-class-name: ${LOCAL_DB_DRIVER}

  flyway:
    enabled: ${LOCAL_IS_ACTIVE:true}
    validate-on-migrate: ${LOCAL_IS_VALIDATE_ON_MIGRATE:true}
    locations: ${LOCAL_MIGRATION_LOCATION:classpath:db/migration}

  jpa:
    show-sql: ${LOCAL_IS_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${LOCAL_DDL_AUTO:create-drop}

server:
  port: ${LOCAL_APPLICATION_PORT:8080}